package com.fangda.maintain.web.model;

import javax.persistence.*;
import java.io.Serializable;

@Table(name = "fd_company")
public class Company implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fd_company.id
     *
     * @mbggenerated
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fd_company.project_id
     *
     * @mbggenerated
     */
    @Column(name = "projectId")
    private Integer projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fd_company.company_name
     *
     * @mbggenerated
     */
    @Column(name = "companyName")
    private String companyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fd_company.company_location
     *
     * @mbggenerated
     */
    @Column(name = "companyLocation")
    private String companyLocation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fd_company.contact_tel
     *
     * @mbggenerated
     */
    @Column(name = "contactTel")
    private String contactTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fd_company.contact_person
     *
     * @mbggenerated
     */
    @Column(name = "contactPerson")
    private String contactPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fd_company.remark
     *
     * @mbggenerated
     */
    @Column(name = "remark")
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fd_company
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fd_company.id
     *
     * @return the value of fd_company.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fd_company.id
     *
     * @param id the value for fd_company.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fd_company.project_id
     *
     * @return the value of fd_company.project_id
     *
     * @mbggenerated
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fd_company.project_id
     *
     * @param projectId the value for fd_company.project_id
     *
     * @mbggenerated
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fd_company.company_name
     *
     * @return the value of fd_company.company_name
     *
     * @mbggenerated
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fd_company.company_name
     *
     * @param companyName the value for fd_company.company_name
     *
     * @mbggenerated
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fd_company.company_location
     *
     * @return the value of fd_company.company_location
     *
     * @mbggenerated
     */
    public String getCompanyLocation() {
        return companyLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fd_company.company_location
     *
     * @param companyLocation the value for fd_company.company_location
     *
     * @mbggenerated
     */
    public void setCompanyLocation(String companyLocation) {
        this.companyLocation = companyLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fd_company.contact_tel
     *
     * @return the value of fd_company.contact_tel
     *
     * @mbggenerated
     */
    public String getContactTel() {
        return contactTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fd_company.contact_tel
     *
     * @param contactTel the value for fd_company.contact_tel
     *
     * @mbggenerated
     */
    public void setContactTel(String contactTel) {
        this.contactTel = contactTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fd_company.contact_person
     *
     * @return the value of fd_company.contact_person
     *
     * @mbggenerated
     */
    public String getContactPerson() {
        return contactPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fd_company.contact_person
     *
     * @param contactPerson the value for fd_company.contact_person
     *
     * @mbggenerated
     */
    public void setContactPerson(String contactPerson) {
        this.contactPerson = contactPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fd_company.remark
     *
     * @return the value of fd_company.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fd_company.remark
     *
     * @param remark the value for fd_company.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fd_company
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Company other = (Company) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getProjectId() == null ? other.getProjectId() == null : this.getProjectId().equals(other.getProjectId()))
            && (this.getCompanyName() == null ? other.getCompanyName() == null : this.getCompanyName().equals(other.getCompanyName()))
            && (this.getCompanyLocation() == null ? other.getCompanyLocation() == null : this.getCompanyLocation().equals(other.getCompanyLocation()))
            && (this.getContactTel() == null ? other.getContactTel() == null : this.getContactTel().equals(other.getContactTel()))
            && (this.getContactPerson() == null ? other.getContactPerson() == null : this.getContactPerson().equals(other.getContactPerson()))
            && (this.getRemark() == null ? other.getRemark() == null : this.getRemark().equals(other.getRemark()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fd_company
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getProjectId() == null) ? 0 : getProjectId().hashCode());
        result = prime * result + ((getCompanyName() == null) ? 0 : getCompanyName().hashCode());
        result = prime * result + ((getCompanyLocation() == null) ? 0 : getCompanyLocation().hashCode());
        result = prime * result + ((getContactTel() == null) ? 0 : getContactTel().hashCode());
        result = prime * result + ((getContactPerson() == null) ? 0 : getContactPerson().hashCode());
        result = prime * result + ((getRemark() == null) ? 0 : getRemark().hashCode());
        return result;
    }
}