package com.fangda.maintain.web.model;

import java.io.Serializable;

public class MaintainType implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fd_maintain_type.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fd_maintain_type.maintain_type
     *
     * @mbggenerated
     */
    private String maintainType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fd_maintain_type.desc
     *
     * @mbggenerated
     */
    private String desc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fd_maintain_type
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fd_maintain_type.id
     *
     * @return the value of fd_maintain_type.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fd_maintain_type.id
     *
     * @param id the value for fd_maintain_type.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fd_maintain_type.maintain_type
     *
     * @return the value of fd_maintain_type.maintain_type
     *
     * @mbggenerated
     */
    public String getMaintainType() {
        return maintainType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fd_maintain_type.maintain_type
     *
     * @param maintainType the value for fd_maintain_type.maintain_type
     *
     * @mbggenerated
     */
    public void setMaintainType(String maintainType) {
        this.maintainType = maintainType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fd_maintain_type.desc
     *
     * @return the value of fd_maintain_type.desc
     *
     * @mbggenerated
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fd_maintain_type.desc
     *
     * @param desc the value for fd_maintain_type.desc
     *
     * @mbggenerated
     */
    public void setDesc(String desc) {
        this.desc = desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fd_maintain_type
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        MaintainType other = (MaintainType) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getMaintainType() == null ? other.getMaintainType() == null : this.getMaintainType().equals(other.getMaintainType()))
            && (this.getDesc() == null ? other.getDesc() == null : this.getDesc().equals(other.getDesc()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fd_maintain_type
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getMaintainType() == null) ? 0 : getMaintainType().hashCode());
        result = prime * result + ((getDesc() == null) ? 0 : getDesc().hashCode());
        return result;
    }
}