package com.fangda.maintain.web.dao.mapper;


import com.fangda.maintain.web.model.MaintainInfo;

public interface MaintainInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fd_maintain_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fd_maintain_info
     *
     * @mbggenerated
     */
    int insert(MaintainInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fd_maintain_info
     *
     * @mbggenerated
     */
    int insertSelective(MaintainInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fd_maintain_info
     *
     * @mbggenerated
     */
    MaintainInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fd_maintain_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MaintainInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fd_maintain_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MaintainInfo record);
}