package com.fangda.maintain.web.dao.mapper;


import com.fangda.maintain.web.model.MccUser;

public interface MccUserMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fd_center_user
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Long userId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fd_center_user
	 * @mbggenerated
	 */
	int insert(MccUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fd_center_user
	 * @mbggenerated
	 */
	int insertSelective(MccUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fd_center_user
	 * @mbggenerated
	 */
	MccUser selectByPrimaryKey(Long userId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fd_center_user
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(MccUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fd_center_user
	 * @mbggenerated
	 */
	int updateByPrimaryKey(MccUser record);
}