package com.fangda.maintain.web.domain;

import java.util.Date;

public class MCCenterUserInputDTO extends BaseInputDTO {
	private String merchantName; //商户名称
	private int pageNo;

	private int pageSize;
	
	private String companyId;
	
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mc_center_user.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mc_center_user.user_name
     *
     * @mbggenerated
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mc_center_user.user_eml
     *
     * @mbggenerated
     */
    private String userEml;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mc_center_user.lgn_pwd
     *
     * @mbggenerated
     */
    private String lgnPwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mc_center_user.pre_mbl
     *
     * @mbggenerated
     */
    private String preMbl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mc_center_user.user_mbl
     *
     * @mbggenerated
     */
    private String userMbl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mc_center_user.first_name
     *
     * @mbggenerated
     */
    private String firstName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mc_center_user.last_name
     *
     * @mbggenerated
     */
    private String lastName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mc_center_user.country_id
     *
     * @mbggenerated
     */
    private Integer countryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mc_center_user.city_id
     *
     * @mbggenerated
     */
    private Integer cityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mc_center_user.user_address
     *
     * @mbggenerated
     */
    private String userAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mc_center_user.user_personal_website
     *
     * @mbggenerated
     */
    private String userPersonalWebsite;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mc_center_user.user_avatar
     *
     * @mbggenerated
     */
    private String userAvatar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mc_center_user.sex
     *
     * @mbggenerated
     */
    private Short sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mc_center_user.birthday
     *
     * @mbggenerated
     */
    private Date birthday;

    /**
     * 用户类型
     */
    private String userType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mc_center_user.reg_from
     *
     * @mbggenerated
     */
    private Short regFrom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mc_center_user.lck_status
     *
     * @mbggenerated
     */
    private Short lckStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mc_center_user.rlv_time
     *
     * @mbggenerated
     */
    private Date rlvTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mc_center_user.rp_token
     *
     * @mbggenerated
     */
    private String rpToken;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mc_center_user.rp_token_created_at
     *
     * @mbggenerated
     */
    private Date rpTokenCreatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mc_center_user.is_deleted
     *
     * @mbggenerated
     */
    private Short isDeleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mc_center_user.opt_counter
     *
     * @mbggenerated
     */
    private Short optCounter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mc_center_user.user_activation_key
     *
     * @mbggenerated
     */
    private String userActivationKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mc_center_user.created_by
     *
     * @mbggenerated
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mc_center_user.updated_by
     *
     * @mbggenerated
     */
    private String updatedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mc_center_user.created_at
     *
     * @mbggenerated
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mc_center_user.updated_at
     *
     * @mbggenerated
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mc_center_user
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mc_center_user.user_id
     *
     * @return the value of mc_center_user.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mc_center_user.user_id
     *
     * @param userId the value for mc_center_user.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mc_center_user.user_name
     *
     * @return the value of mc_center_user.user_name
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mc_center_user.user_name
     *
     * @param userName the value for mc_center_user.user_name
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mc_center_user.user_eml
     *
     * @return the value of mc_center_user.user_eml
     *
     * @mbggenerated
     */
    public String getUserEml() {
        return userEml;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mc_center_user.user_eml
     *
     * @param userEml the value for mc_center_user.user_eml
     *
     * @mbggenerated
     */
    public void setUserEml(String userEml) {
        this.userEml = userEml;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mc_center_user.lgn_pwd
     *
     * @return the value of mc_center_user.lgn_pwd
     *
     * @mbggenerated
     */
    public String getLgnPwd() {
        return lgnPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mc_center_user.lgn_pwd
     *
     * @param lgnPwd the value for mc_center_user.lgn_pwd
     *
     * @mbggenerated
     */
    public void setLgnPwd(String lgnPwd) {
        this.lgnPwd = lgnPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mc_center_user.pre_mbl
     *
     * @return the value of mc_center_user.pre_mbl
     *
     * @mbggenerated
     */
    public String getPreMbl() {
        return preMbl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mc_center_user.pre_mbl
     *
     * @param preMbl the value for mc_center_user.pre_mbl
     *
     * @mbggenerated
     */
    public void setPreMbl(String preMbl) {
        this.preMbl = preMbl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mc_center_user.user_mbl
     *
     * @return the value of mc_center_user.user_mbl
     *
     * @mbggenerated
     */
    public String getUserMbl() {
        return userMbl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mc_center_user.user_mbl
     *
     * @param userMbl the value for mc_center_user.user_mbl
     *
     * @mbggenerated
     */
    public void setUserMbl(String userMbl) {
        this.userMbl = userMbl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mc_center_user.first_name
     *
     * @return the value of mc_center_user.first_name
     *
     * @mbggenerated
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mc_center_user.first_name
     *
     * @param firstName the value for mc_center_user.first_name
     *
     * @mbggenerated
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mc_center_user.last_name
     *
     * @return the value of mc_center_user.last_name
     *
     * @mbggenerated
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mc_center_user.last_name
     *
     * @param lastName the value for mc_center_user.last_name
     *
     * @mbggenerated
     */
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mc_center_user.country_id
     *
     * @return the value of mc_center_user.country_id
     *
     * @mbggenerated
     */
    public Integer getCountryId() {
        return countryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mc_center_user.country_id
     *
     * @param countryId the value for mc_center_user.country_id
     *
     * @mbggenerated
     */
    public void setCountryId(Integer countryId) {
        this.countryId = countryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mc_center_user.city_id
     *
     * @return the value of mc_center_user.city_id
     *
     * @mbggenerated
     */
    public Integer getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mc_center_user.city_id
     *
     * @param cityId the value for mc_center_user.city_id
     *
     * @mbggenerated
     */
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mc_center_user.user_address
     *
     * @return the value of mc_center_user.user_address
     *
     * @mbggenerated
     */
    public String getUserAddress() {
        return userAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mc_center_user.user_address
     *
     * @param userAddress the value for mc_center_user.user_address
     *
     * @mbggenerated
     */
    public void setUserAddress(String userAddress) {
        this.userAddress = userAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mc_center_user.user_personal_website
     *
     * @return the value of mc_center_user.user_personal_website
     *
     * @mbggenerated
     */
    public String getUserPersonalWebsite() {
        return userPersonalWebsite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mc_center_user.user_personal_website
     *
     * @param userPersonalWebsite the value for mc_center_user.user_personal_website
     *
     * @mbggenerated
     */
    public void setUserPersonalWebsite(String userPersonalWebsite) {
        this.userPersonalWebsite = userPersonalWebsite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mc_center_user.user_avatar
     *
     * @return the value of mc_center_user.user_avatar
     *
     * @mbggenerated
     */
    public String getUserAvatar() {
        return userAvatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mc_center_user.user_avatar
     *
     * @param userAvatar the value for mc_center_user.user_avatar
     *
     * @mbggenerated
     */
    public void setUserAvatar(String userAvatar) {
        this.userAvatar = userAvatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mc_center_user.sex
     *
     * @return the value of mc_center_user.sex
     *
     * @mbggenerated
     */
    public Short getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mc_center_user.sex
     *
     * @param sex the value for mc_center_user.sex
     *
     * @mbggenerated
     */
    public void setSex(Short sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mc_center_user.birthday
     *
     * @return the value of mc_center_user.birthday
     *
     * @mbggenerated
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mc_center_user.birthday
     *
     * @param birthday the value for mc_center_user.birthday
     *
     * @mbggenerated
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mc_center_user.reg_from
     *
     * @return the value of mc_center_user.reg_from
     *
     * @mbggenerated
     */
    public Short getRegFrom() {
        return regFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mc_center_user.reg_from
     *
     * @param regFrom the value for mc_center_user.reg_from
     *
     * @mbggenerated
     */
    public void setRegFrom(Short regFrom) {
        this.regFrom = regFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mc_center_user.lck_status
     *
     * @return the value of mc_center_user.lck_status
     *
     * @mbggenerated
     */
    public Short getLckStatus() {
        return lckStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mc_center_user.lck_status
     *
     * @param lckStatus the value for mc_center_user.lck_status
     *
     * @mbggenerated
     */
    public void setLckStatus(Short lckStatus) {
        this.lckStatus = lckStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mc_center_user.rlv_time
     *
     * @return the value of mc_center_user.rlv_time
     *
     * @mbggenerated
     */
    public Date getRlvTime() {
        return rlvTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mc_center_user.rlv_time
     *
     * @param rlvTime the value for mc_center_user.rlv_time
     *
     * @mbggenerated
     */
    public void setRlvTime(Date rlvTime) {
        this.rlvTime = rlvTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mc_center_user.rp_token
     *
     * @return the value of mc_center_user.rp_token
     *
     * @mbggenerated
     */
    public String getRpToken() {
        return rpToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mc_center_user.rp_token
     *
     * @param rpToken the value for mc_center_user.rp_token
     *
     * @mbggenerated
     */
    public void setRpToken(String rpToken) {
        this.rpToken = rpToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mc_center_user.rp_token_created_at
     *
     * @return the value of mc_center_user.rp_token_created_at
     *
     * @mbggenerated
     */
    public Date getRpTokenCreatedAt() {
        return rpTokenCreatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mc_center_user.rp_token_created_at
     *
     * @param rpTokenCreatedAt the value for mc_center_user.rp_token_created_at
     *
     * @mbggenerated
     */
    public void setRpTokenCreatedAt(Date rpTokenCreatedAt) {
        this.rpTokenCreatedAt = rpTokenCreatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mc_center_user.is_deleted
     *
     * @return the value of mc_center_user.is_deleted
     *
     * @mbggenerated
     */
    public Short getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mc_center_user.is_deleted
     *
     * @param isDeleted the value for mc_center_user.is_deleted
     *
     * @mbggenerated
     */
    public void setIsDeleted(Short isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mc_center_user.opt_counter
     *
     * @return the value of mc_center_user.opt_counter
     *
     * @mbggenerated
     */
    public Short getOptCounter() {
        return optCounter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mc_center_user.opt_counter
     *
     * @param optCounter the value for mc_center_user.opt_counter
     *
     * @mbggenerated
     */
    public void setOptCounter(Short optCounter) {
        this.optCounter = optCounter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mc_center_user.user_activation_key
     *
     * @return the value of mc_center_user.user_activation_key
     *
     * @mbggenerated
     */
    public String getUserActivationKey() {
        return userActivationKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mc_center_user.user_activation_key
     *
     * @param userActivationKey the value for mc_center_user.user_activation_key
     *
     * @mbggenerated
     */
    public void setUserActivationKey(String userActivationKey) {
        this.userActivationKey = userActivationKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mc_center_user.created_by
     *
     * @return the value of mc_center_user.created_by
     *
     * @mbggenerated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mc_center_user.created_by
     *
     * @param createdBy the value for mc_center_user.created_by
     *
     * @mbggenerated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mc_center_user.updated_by
     *
     * @return the value of mc_center_user.updated_by
     *
     * @mbggenerated
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mc_center_user.updated_by
     *
     * @param updatedBy the value for mc_center_user.updated_by
     *
     * @mbggenerated
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mc_center_user.created_at
     *
     * @return the value of mc_center_user.created_at
     *
     * @mbggenerated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mc_center_user.created_at
     *
     * @param createdAt the value for mc_center_user.created_at
     *
     * @mbggenerated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mc_center_user.updated_at
     *
     * @return the value of mc_center_user.updated_at
     *
     * @mbggenerated
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mc_center_user.updated_at
     *
     * @param updatedAt the value for mc_center_user.updated_at
     *
     * @mbggenerated
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

	public String getUserType() {
		return userType;
	}

	public void setUserType(String userType) {
		this.userType = userType;
	}

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mc_center_user
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        MCCenterUserInputDTO other = (MCCenterUserInputDTO) that;
        return (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getUserName() == null ? other.getUserName() == null : this.getUserName().equals(other.getUserName()))
            && (this.getUserEml() == null ? other.getUserEml() == null : this.getUserEml().equals(other.getUserEml()))
            && (this.getLgnPwd() == null ? other.getLgnPwd() == null : this.getLgnPwd().equals(other.getLgnPwd()))
            && (this.getPreMbl() == null ? other.getPreMbl() == null : this.getPreMbl().equals(other.getPreMbl()))
            && (this.getUserMbl() == null ? other.getUserMbl() == null : this.getUserMbl().equals(other.getUserMbl()))
            && (this.getFirstName() == null ? other.getFirstName() == null : this.getFirstName().equals(other.getFirstName()))
            && (this.getLastName() == null ? other.getLastName() == null : this.getLastName().equals(other.getLastName()))
            && (this.getCountryId() == null ? other.getCountryId() == null : this.getCountryId().equals(other.getCountryId()))
            && (this.getCityId() == null ? other.getCityId() == null : this.getCityId().equals(other.getCityId()))
            && (this.getUserAddress() == null ? other.getUserAddress() == null : this.getUserAddress().equals(other.getUserAddress()))
            && (this.getUserPersonalWebsite() == null ? other.getUserPersonalWebsite() == null : this.getUserPersonalWebsite().equals(other.getUserPersonalWebsite()))
            && (this.getUserAvatar() == null ? other.getUserAvatar() == null : this.getUserAvatar().equals(other.getUserAvatar()))
            && (this.getSex() == null ? other.getSex() == null : this.getSex().equals(other.getSex()))
            && (this.getBirthday() == null ? other.getBirthday() == null : this.getBirthday().equals(other.getBirthday()))
            && (this.getRegFrom() == null ? other.getRegFrom() == null : this.getRegFrom().equals(other.getRegFrom()))
            && (this.getLckStatus() == null ? other.getLckStatus() == null : this.getLckStatus().equals(other.getLckStatus()))
            && (this.getRlvTime() == null ? other.getRlvTime() == null : this.getRlvTime().equals(other.getRlvTime()))
            && (this.getRpToken() == null ? other.getRpToken() == null : this.getRpToken().equals(other.getRpToken()))
            && (this.getRpTokenCreatedAt() == null ? other.getRpTokenCreatedAt() == null : this.getRpTokenCreatedAt().equals(other.getRpTokenCreatedAt()))
            && (this.getIsDeleted() == null ? other.getIsDeleted() == null : this.getIsDeleted().equals(other.getIsDeleted()))
            && (this.getOptCounter() == null ? other.getOptCounter() == null : this.getOptCounter().equals(other.getOptCounter()))
            && (this.getUserActivationKey() == null ? other.getUserActivationKey() == null : this.getUserActivationKey().equals(other.getUserActivationKey()))
            && (this.getCreatedBy() == null ? other.getCreatedBy() == null : this.getCreatedBy().equals(other.getCreatedBy()))
            && (this.getUpdatedBy() == null ? other.getUpdatedBy() == null : this.getUpdatedBy().equals(other.getUpdatedBy()))
            && (this.getCreatedAt() == null ? other.getCreatedAt() == null : this.getCreatedAt().equals(other.getCreatedAt()))
            && (this.getUpdatedAt() == null ? other.getUpdatedAt() == null : this.getUpdatedAt().equals(other.getUpdatedAt()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mc_center_user
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getUserName() == null) ? 0 : getUserName().hashCode());
        result = prime * result + ((getUserEml() == null) ? 0 : getUserEml().hashCode());
        result = prime * result + ((getLgnPwd() == null) ? 0 : getLgnPwd().hashCode());
        result = prime * result + ((getPreMbl() == null) ? 0 : getPreMbl().hashCode());
        result = prime * result + ((getUserMbl() == null) ? 0 : getUserMbl().hashCode());
        result = prime * result + ((getFirstName() == null) ? 0 : getFirstName().hashCode());
        result = prime * result + ((getLastName() == null) ? 0 : getLastName().hashCode());
        result = prime * result + ((getCountryId() == null) ? 0 : getCountryId().hashCode());
        result = prime * result + ((getCityId() == null) ? 0 : getCityId().hashCode());
        result = prime * result + ((getUserAddress() == null) ? 0 : getUserAddress().hashCode());
        result = prime * result + ((getUserPersonalWebsite() == null) ? 0 : getUserPersonalWebsite().hashCode());
        result = prime * result + ((getUserAvatar() == null) ? 0 : getUserAvatar().hashCode());
        result = prime * result + ((getSex() == null) ? 0 : getSex().hashCode());
        result = prime * result + ((getBirthday() == null) ? 0 : getBirthday().hashCode());
        result = prime * result + ((getRegFrom() == null) ? 0 : getRegFrom().hashCode());
        result = prime * result + ((getLckStatus() == null) ? 0 : getLckStatus().hashCode());
        result = prime * result + ((getRlvTime() == null) ? 0 : getRlvTime().hashCode());
        result = prime * result + ((getRpToken() == null) ? 0 : getRpToken().hashCode());
        result = prime * result + ((getRpTokenCreatedAt() == null) ? 0 : getRpTokenCreatedAt().hashCode());
        result = prime * result + ((getIsDeleted() == null) ? 0 : getIsDeleted().hashCode());
        result = prime * result + ((getOptCounter() == null) ? 0 : getOptCounter().hashCode());
        result = prime * result + ((getUserActivationKey() == null) ? 0 : getUserActivationKey().hashCode());
        result = prime * result + ((getCreatedBy() == null) ? 0 : getCreatedBy().hashCode());
        result = prime * result + ((getUpdatedBy() == null) ? 0 : getUpdatedBy().hashCode());
        result = prime * result + ((getCreatedAt() == null) ? 0 : getCreatedAt().hashCode());
        result = prime * result + ((getUpdatedAt() == null) ? 0 : getUpdatedAt().hashCode());
        return result;
    }

	public int getPageNo() {
		return pageNo;
	}

	public int getPageSize() {
		return pageSize;
	}

	public void setPageNo(int pageNo) {
		this.pageNo = pageNo;
	}

	public void setPageSize(int pageSize) {
		this.pageSize = pageSize;
	}

	public String getCompanyId() {
		return companyId;
	}

	public void setCompanyId(String companyId) {
		this.companyId = companyId;
	}

	public String getMerchantName() {
		return merchantName;
	}

	public void setMerchantName(String merchantName) {
		this.merchantName = merchantName;
	}

}